# NumPy arrays

In [1]:
import numpy as np

In [2]:
p = np.array([48.858598, 2.294495])

In [3]:
p

array([48.858598,  2.294495])

In [4]:
p.ndim

1

In [5]:
p.shape

(2,)

In [6]:
len(p)

2

In [7]:
p.dtype

dtype('float64')

### Convert dtype

In [11]:
a = np.array([1, 2, 3, 4])

In [12]:
a.dtype

dtype('int32')

In [13]:
float_b = a.astype(np.float64)

In [14]:
float_b.dtype

dtype('float64')

### Array creation

In [25]:
# -- empty

In [16]:
np.empty([3,2], dtype=np.float64)

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [ ]:
# (np.empty_like WRONG!)

In [28]:
# -- eye

In [29]:
np.eye(2, dtype=np.int)

array([[1, 0],
       [0, 1]])

In [30]:
# -- ones

In [31]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [32]:
np.ones(4, dtype=np.int)

array([1, 1, 1, 1])

In [33]:
x = np.array([[0,1,2], [3,4,5]])

In [34]:
x

array([[0, 1, 2],
       [3, 4, 5]])

In [35]:
np.ones_like(x)

array([[1, 1, 1],
       [1, 1, 1]])

In [ ]:
# -- zeros

In [36]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [37]:
np.zeros(4, dtype=np.int)

array([0, 0, 0, 0])

In [38]:
x = np.array([[0,1,2], [3,4,5]])

In [39]:
x

array([[0, 1, 2],
       [3, 4, 5]])

In [40]:
np.zeros_like(x)

array([[0, 0, 0],
       [0, 0, 0]])

In [43]:
# -- arange

In [41]:
np.arange(2, 5)

array([2, 3, 4])

In [42]:
np.arange(4, 12, 5)

array([4, 9])

In [ ]:
# -- full

In [44]:
np.full( (2,2), 3, dtype=np.int )

array([[3, 3],
       [3, 3]])

In [45]:
x = np.ones(3)

In [46]:
x

array([1., 1., 1.])

In [47]:
np.full_like(x, 2)

array([2., 2., 2.])

In [48]:
# -- array

In [49]:
np.array([ [1.1, 2.2, 3.3], [4.4, 5.5, 6.6] ])

array([[1.1, 2.2, 3.3],
       [4.4, 5.5, 6.6]])

In [50]:
# -- asarray

In [51]:
a = [3.14, 2.46]

In [52]:
a

[3.14, 2.46]

In [53]:
np.asarray(a)

array([3.14, 2.46])

In [54]:
# -- copy 

In [55]:
a = np.array([[1, 2], [3, 4]])

In [56]:
np.copy(a)

array([[1, 2],
       [3, 4]])

In [57]:
# -- fromstring

In [58]:
np.fromstring('3.14 2.17', dtype=np.float, sep=' ')

array([3.14, 2.17])

### Indexing and slicing

In [59]:
a = np.arange(7)

In [60]:
a

array([0, 1, 2, 3, 4, 5, 6])

In [61]:
a[1], a[4], a[-1]

(1, 4, 6)

In [62]:
a = np.array([ [1, 2, 3], [4, 5, 6], [7, 8, 9] ])

In [63]:
a[0, 2] # first row 0, third column 2

3

In [64]:
a[0, 2] = 10

In [65]:
a

array([[ 1,  2, 10],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [66]:
b = a[2]

In [67]:
b

array([7, 8, 9])

In [68]:
c = a[:2]

In [69]:
c

array([[ 1,  2, 10],
       [ 4,  5,  6]])

In [72]:
b[-1] = 11 # copied by pointer, so it changes both 'a' and 'b'. 

In [71]:
a

array([[ 1,  2, 10],
       [ 4,  5,  6],
       [ 7,  8, 11]])

### Fancy indexing

In [74]:
a = np.array([3, 5, 1, 10])

In [75]:
b = (a % 5 == 0)

In [76]:
b

array([False,  True, False,  True])

In [77]:
c = np.array([ [0, 1], [2, 3], [4, 5], [6, 7] ])

In [79]:
c[b]  # Because 'b' value is '[False, True, False, True]' --> returns 2nd and 4th lists,
      # i.e., [2, 3]  and [6, 7]

array([[2, 3],
       [6, 7]])

In [80]:
a = np.array([ [1 ,  2,  3,  4],
               [5 ,  6,  7,  8],
               [9 , 10, 11, 12],
               [13, 14, 15, 16]
             ])

In [81]:
a[[2, 1]]

array([[ 9, 10, 11, 12],
       [ 5,  6,  7,  8]])

In [82]:
a[[1, 2]]

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [83]:
a[[-2, -1]]                 # select rows from the end.

array([[ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [84]:
a[ [2, 3], [0, 1] ]         # take elements at (2, 0) and (3, 1)

array([ 9, 14])

In [87]:
'''
 1,  2,  3,  4,                  (2, 3) X (0, 1) = 2,0    and   3,1
 5,  6,  7,  8,                     2,0 --> 9
 9, 10, 11, 12,                     3,1 --> 14
13, 14, 15, 16
'''

'\n 1,  2,  3,  4,                  (2, 3) X (0, 1) = 2,0    and   3,1\n 5,  6,  7,  8,                     2,0 --> 9\n 9, 10, 11, 12,                     3,1 --> 14\n13, 14, 15, 16\n'

In [86]:
a[[2, 3]]

array([[ 9, 10, 11, 12],
       [13, 14, 15, 16]])

### Numerical operations on arrays

In [138]:
a = np.ones(4)

In [139]:
a

array([1., 1., 1., 1.])

In [140]:
a * 2

array([2., 2., 2., 2.])

In [141]:
a + 3

array([4., 4., 4., 4.])

In [142]:
a = np.ones([2, 4])

In [143]:
a

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [144]:
a * a

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [145]:
a + a

array([[2., 2., 2., 2.],
       [2., 2., 2., 2.]])

In [146]:
a = np.array([1, 2, 3, 4])
b = np.array([1, 1, 5, 3])

In [147]:
a == b

array([ True, False, False, False])

In [148]:
np.array_equal(a, b)

False

In [150]:
c = np.array([1, 0])
d = np.array([1, 1])

In [151]:
np.logical_and(c, d)

array([ True, False])

### Array Functions

In [88]:
a = np.array([ [0, 5, 10], [20, 25, 30] ])

In [89]:
a

array([[ 0,  5, 10],
       [20, 25, 30]])

In [90]:
a.reshape(3, 2)

array([[ 0,  5],
       [10, 20],
       [25, 30]])

In [93]:
a

array([[ 0,  5, 10],
       [20, 25, 30]])

In [91]:
a.T

array([[ 0, 20],
       [ 5, 25],
       [10, 30]])

In [95]:
a = np.array([ [[0, 1, 2], [3, 4, 5]], 
               [[6, 7, 8], [9, 10, 11]]
             ])

In [96]:
a.swapaxes(1, 2)

array([[[ 0,  3],
        [ 1,  4],
        [ 2,  5]],

       [[ 6,  9],
        [ 7, 10],
        [ 8, 11]]])

In [99]:
a.swapaxes(0, 2)

array([[[ 0,  6],
        [ 3,  9]],

       [[ 1,  7],
        [ 4, 10]],

       [[ 2,  8],
        [ 5, 11]]])

In [100]:
a = np.array([ [1, 2, 3], [4, 5, 6] ])

In [101]:
np.dot(a.T, a)

array([[17, 22, 27],
       [22, 29, 36],
       [27, 36, 45]])

In [118]:
a = np.array([ [6, 34, 1, 6], [0, 5, 2, -1] ])

In [119]:
np.sort(a)   # sort along the last axis

array([[ 1,  6,  6, 34],
       [-1,  0,  2,  5]])

In [120]:
np.sort(a, axis=0)    # sort along the first axis

array([[ 0,  5,  1, -1],
       [ 6, 34,  2,  6]])

In [121]:
b = np.argsort(a)     # fancy indexing of sorted array

In [122]:
b     # ?

array([[2, 0, 3, 1],
       [3, 0, 2, 1]], dtype=int64)

In [123]:
a[0][b[0]]

array([ 1,  6,  6, 34])

In [124]:
a[0]

array([ 6, 34,  1,  6])

In [125]:
np.argmax(a)          # get index of maximum element

1

In [126]:
# Trigonometric and hyperbolic functions
# sin, cos, tan, cosh, sinh, tanh, arcos, arctan, deg2rad

In [127]:
a = np.array( [0., 30., 45.] )

In [129]:
np.sin(a*np.pi / 180)

array([0.        , 0.5       , 0.70710678])

In [130]:
# Rounding elements of an array to the given or nearest number 
# around, round, rint, fix, floor, ceil, trunc

In [131]:
a = np.array( [0.34, 1.65])

In [132]:
np.round(a)

array([0., 2.])

In [133]:
# Computing the exponents and logarithms of an array 
# sqrt, square, exp, expml, exp2, log, log10, log1p, logaddexp

In [135]:
np.exp(np.array( [2.25, 3.16] ))

array([ 9.48773584, 23.57059593])

In [136]:
np.exp(2.25)

9.487735836358526

In [137]:
np.exp(3.16)

23.570595929068126

In [152]:
# Set of arithmetic functions on arrays
# add, negative, multiply, devide, power, substract, mod, modf, remainder

In [154]:
a = np.arange(6)

In [155]:
a

array([0, 1, 2, 3, 4, 5])

In [156]:
x1 = a.reshape(2, 3)

In [157]:
x1

array([[0, 1, 2],
       [3, 4, 5]])

In [158]:
x2 = np.arange(3)

In [159]:
x2

array([0, 1, 2])

In [160]:
np.multiply(x1, x2)

array([[ 0,  1,  4],
       [ 0,  4, 10]])

In [ ]:
# 